apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
  namespace: example
spec:
  template:
    spec:
      containers:
        - name: myapp
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "256Mi"
              cpu: "500m"

